#  menu items
#[[main]]
#  name = "Drivers"
#  weight = 2
#  url = "drivers/"

[[main]]
  name = "About"
  weight = 5
  url = "about/"

[[main]]
  name = "HTA Generator"
  weight = 6
  url = "https://htagen.loldrivers.io"

[[main]]
  name = "Premium"
  weight = 7
  url = "https://www.magicsword.io/premium"
