name: Deploy Site

on:
  workflow_run:
    workflows: [Generate Site]
    types: [completed]

jobs:
    # Build job
    build:
      runs-on: ubuntu-latest
      env:
        HUGO_VERSION: 0.111.3
      steps:
        - name: Harden the runner (Audit all outbound calls)
          uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
          with:
            egress-policy: audit

        - name: Install Hugo CLI
          run: |
            wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
            && sudo dpkg -i ${{ runner.temp }}/hugo.deb          
        - name: Install Dart Sass Embedded
          run: sudo snap install dart-sass-embedded
        - name: Checkout
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            submodules: true
            token: ${{ secrets.PUSH_TOKEN }}
        - name: Setup Pages
          id: pages
          uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
        - name: Install Node.js dependencies
          run: |
            cd loldrivers.io/
            [[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true
        - name: Build with Hugo
          env:
            # For maximum backward compatibility with Hugo modules
            HUGO_ENVIRONMENT: production
            HUGO_ENV: production
          run: |
            cd loldrivers.io/
            hugo \
              --gc \
              --minify \
              --baseURL "${{ steps.pages.outputs.base_url }}/"
        - name: Upload artifact
          uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
          with:
            path: ./loldrivers.io/public
  
    # Deployment job
    deploy:
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        permissions:
          pages: write
          id-token: write
        steps:
          - name: Harden the runner (Audit all outbound calls)
            uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
            with:
              egress-policy: audit

          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5