name: Create the drivers folder artifact
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create_artifact:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Build drivers.zip
        run: |
          mkdir -p build/metadata
          mkdir -p build/drivers
          cp -r yaml/ build/metadata
          cp -r drivers/ build/drivers
          cd build
          zip -r drivers.zip metadata/ drivers/
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Drivers
          path: build\drivers.zip
