name: Generate WDAC denylist

on: 
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  generate-wdac:
    runs-on: windows-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: false
        lfs: true
    - name: Scan drivers
      shell: powershell
      run: |
        Get-ChildItem .\drivers\*.bin | Rename-Item -newname { $_.name -replace '.bin','.sys' };
        $drivers = Get-SystemDriver -ScanPath .\drivers\ -NoShadowCopy;
        $NewDriverRules = New-CIPolicyRule -DriverFiles $drivers -Level FilePublisher -Fallback SignedVersion,Publisher,Hash -Deny;
        Merge-CIPolicy -OutputFilePath Denylist.xml -PolicyPaths C:\Windows\schemas\CodeIntegrity\ExamplePolicies\AllowAll.xml -Rules $NewDriverRules | Out-Null;
    - name: Upload artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: Denylist
        path: Denylist.xml
