name: "HVCI Tag Update"

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run_powershell:
    runs-on: windows-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Run PowerShell script
      run: |
        Invoke-WebRequest -Uri "https://gist.github.com/MHaggis/8d6de45b883b338e47de08b3cb4c9819" -OutFile "script.ps1"
        ./script.ps1
    - name: Upload CSV
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: hvci_drivers
        path: bin/hvci_drivers.csv

  run_python:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    needs: run_powershell
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Download CSV
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: hvci_drivers
        path: bin/
    - name: Set up Python 3.13
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        pip install PyYAML argparse requests
    - name: Execute Python script
      run: |
        python bin/hvcitag.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        reviewers: nasbench, mhaggis
        delete-branch: true
        branch: 'create-pull-request/hvciupdate'
        commit-message: 'chore: update hvci check'
        title: 'HVCI Tag Update'
        body: |
          ### Summary of the Pull Request

          This PR updates the HVCI tagging based on new drivers added to the project.
