name: Validate YAMLs

on: 
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: true
    - name: Set up Python 3.13
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: 3.13
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python -
    - name: Install dependencies with Poetry
      run: poetry install
    - name: Run YAML Checks
      run: poetry run python bin/validate.py -v
